apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod1-sa
  namespace: stg
---
# Pod 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      serviceAccountName: pod1-sa
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: nodejs-app
          image: "wklcicd.azurecr.io/nodejs-app:{{imageTag}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: stg
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stg
  name: pod1-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod1-rolebinding
  namespace: stg
subjects:
  - kind: ServiceAccount
    name: pod1-sa
    namespace: stg
roleRef:
  kind: Role
  name: pod1-role
  apiGroup: rbac.authorization.k8s.io
